Replaced asserts in user-callable functions with luaL_argcheck
FTL-Hyperspace/FTL-Hyperspace pull request #112
Opened 2023-05-12 15:44 UTC by Vertaalfout

Now improper arguments to lua functions will result in easy-to-understand lua errors, instead of assertion fails.

2023-06-07 16:09 UTC, Nasa62 requested changes
My only concern here is that `luaL_argcheck` might not abort the execution?

`assert` I think also stopped the C/C++ function from continuing it's execution (like issuing a `return`)

Can we validate that it actually stops execution of the function? and/or have both or detect the lua error and stop execution?

2023-06-07 16:29 UTC, ChronoVortex commented
> Can we validate that it actually stops execution of the function? and/or have both or detect the lua error and stop execution?

`luaL_argcheck` aborted execution of the LUA script when I tested.

2023-06-07 16:42 UTC, Nasa62 commented
> `luaL_argcheck` aborted execution of the LUA script when I tested.

Yes but I'm talking about the C-execution of that function where we're still doing other things

2023-06-07 16:47 UTC, ChronoVortex commented
> Yes but I'm talking about the C-execution of that function where we're still doing other things

Doesn't an error being raised stop execution of the function in C?

2023-06-08 00:07 UTC, Nasa62 commented
> > Yes but I'm talking about the C-execution of that function where we're still doing other things
> 
> Doesn't an error being raised stop execution of the function in C?

I don't know, if it does, great. Does it?

2023-06-08 01:12 UTC, ChronoVortex commented
> I don't know, if it does, great. Does it?

```c++
#include <iostream>
#include <string>

void test() {
    throw 0;
    std::cout << "Hello, world" << std::endl;
}

int main() {
    try {
        test();
    } catch (int e) {
        std::cout << "An exception occurred. Exception #" << e << std::endl;
    }
}
```
```
An exception occurred. Exception #0
```
Yes.

2023-06-08 15:59 UTC, Nasa62 approved these changes
Cool then this is good

2023-06-08 16:00 UTC, merged