Make recallBoarders always recall player crew regardless of whether they can teleport OR make it an attribute
FTL-Hyperspace/FTL-Hyperspace pull request #251
Opened 2024-03-05 02:44 UTC by Choosechee

Right now, recallBoarders doesn't recall player crew who can't teleport. This is really bad for the way Multiverse uses it, since these crew will be lost unfairly. For some reason, a check for whether a crew can teleport is directly in the RecallBoarders method itself. I thought it was an oversight where it calls a method used to teleport crew, and that method checks if a crew can teleport, but it seems to have been intentional. I have removed the check in the player crew part of the method but have kept it in for the enemy crew part, since I see some use cases for this. However, since checking if a player crew can teleport seems to have been intentional, another option could be to add an attribute to it that determines whether it recalls crew that can teleport.

2024-03-07 10:32 UTC, ChronoVortex reviewed
Changes like this aren't great for backwards compatibility. Instead of removing the check entirely, you should add an attribute to the `recallBoarders` tag which determines whether all crew are recalled or just the ones that can teleport.

2024-03-07 20:36 UTC, Choosechee commented
Alright, I've made it an attribute.

2024-03-08 02:13 UTC, ChronoVortex requested changes

2024-03-08 02:13 UTC, ChronoVortex commented on CustomEvents.cpp
> +			if (child->first_attribute("force"))
This line uses the wrong kind of indentation, should be four spaces instead of the tab character.

2024-03-08 02:13 UTC, ChronoVortex commented on CustomEvents.h
> +	bool recallBoardersForce = false;
Wrong indentation here too.

2024-04-06 23:04 UTC, ChronoVortex approved these changes

2024-04-06 23:05 UTC, merged