Expose Equipment
FTL-Hyperspace/FTL-Hyperspace pull request #261
Opened 2024-03-25 01:35 UTC by Choosechee

Right now, there's no way in Lua to check the cargo or add items to it. Exposing Equipment seems like it will provide methods that allow you to do this. I  couldn't get this to work on my end, but I decided to make it a pull request so that you can see what I did and help me to get it working. I also fixed the unk Booleans in the AddWeapon, AddDrone, and AddAugmentation methods.

2024-03-26 17:16 UTC, Nasa62 requested changes
Please add Wiki changes

2024-03-26 20:34 UTC, Choosechee commented
> Please add Wiki changes

Done.

2024-04-07 07:07 UTC, THETASOLA requested changes
Error: '[string "data/testwep.lua"]:36: Error in Equipment::AddToCargo (arg 2), expected 'std::string &' got 'string''

For Equipment::AddToCargo you'll need to change the `std::string` to `const std::string` in the zhl.

2024-04-09 07:24 UTC, THETASOLA approved these changes

2024-04-12 00:10 UTC, ChronoVortex approved these changes

2024-04-12 00:11 UTC, merged