New command "SWITCH [SHIPBP_NAME]" allowing the replacement of current ship with the specified blueprint
FTL-Hyperspace/FTL-Hyperspace pull request #285
Opened 2024-05-05 07:11 UTC by THETASOLA

The original intention was to having this method exposed, but during testing it has been discovered that plainly switching ship (in the hangars or with the command) causes memory leak, and lua would allow for too much liberty on spamming a memory leak intensive command.

Until the cause of those leak is found (specific to HS) the method will have to remain simply unexposed in a command.

This method required the use of two new sigs (not all OS sigs have been taken, will need to add them):
- CommandGUI::LinkShip (window/AMD64)
- ScoreKeeper::SetShipBlueprint (window)

2024-05-05 20:46 UTC, THETASOLA commented
The build fails because of the missing sigs for amd64 and x86

2024-08-02 09:50 UTC, ChronoVortex requested changes
Unfortunately this feature is still cursed to high hell. Leaving the last segfault backtrace recorded on Linux here for reference.
```
#0  __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:872
#1  0x000000000072b060 in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) ()
#2  0x000000000072b73c in std::string::assign(std::string const&) ()
#3  0x00000000004d443d in std::string::operator= (
    __str="i\001g"..., this=0xaccfcd8)
    at /usr/include/c++/4.8/bits/basic_string.h:547
#4  TextString::operator= (this=0xaccfcd8)
    at /media/sf_FTL/Project/src/Utilities/Globals.h:245
#5  Description::operator= (this=0xaccfcd8)
    at /media/sf_FTL/Project/src/Gameplay/World/BlueprintManager.h:100
#6  ShipBlueprint::operator= (this=this@entry=0xaccfc60)
    at /media/sf_FTL/Project/src/Gameplay/World/BlueprintManager.h:190
#7  0x00000000004cb490 in ShipManager::OnInit (this=0xaccf5e0, 
    bluePrint=<optimized out>, level=0) at /media/sf_FTL/Project/src/Ship/ShipManager.cpp:754
#8  0x00007ffff7bcb0c6 in (anonymous namespace)::Hook_186::wrapper::super<ShipBlueprint*&, int&> (this=0xaccf5e0, args=@0x7fffffff964c: 0, args=@0x7fffffff964c: 0) at /workspaces/FTL-Hyperspace/CustomShips.cpp:186
#9  0x00007ffff7bc4378 in (anonymous namespace)::Hook_186::wrapper::hook (this=0xaccf5e0, bp=0xb76fbe8, shipLevel=0) at /workspaces/FTL-Hyperspace/CustomShips.cpp:189
#10 0x00007ffff7c3235f in ShipManager::OnInit (this=0xaccf5e0, bp=0xb76fbe8, shipLevel=0) at /workspaces/FTL-Hyperspace/FTLGameELF64.cpp:13497
#11 0x00007ffff79fe4b0 in CommandConsole::SwitchShip (this=0x7ffff7e2d422 <CommandConsole::instance>, shipBlueprint=0xb76fbe8) at /workspaces/FTL-Hyperspace/CommandConsole.cpp:342
```

2024-12-10 15:47 UTC, THETASOLA commented
Putting it as a draft to avoid confusion.

2025-01-31 10:46 UTC, THETASOLA commented
This will need to be moved to its own file, have an xml tag in event, have lua exposure, have an helper method that keeps crew/weapon/cargo/upgrades between old and new ship.

The crashes are probably caused by dangling pointers not updated, since so many system have their own pointer of the shipmanager.

2025-02-05 18:50 UTC, THETASOLA commented
Closing it since https://github.com/FTL-Hyperspace/FTL-Hyperspace/pull/471 replaces it. I will not miss it for one bit.

2025-02-05 18:50 UTC, closed without merging